server:
  port: 8002
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: UserProvider
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.jbt.model
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka,http://localhost:9999/eureka
